server:
  port: 80

#服务别名----注册zookeeper到注册中心的名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到zookeeper地址
    zookeeper:
      #换成自己的ip
      connect-string: 192.168.190.128:2181